In [45]:
import numpy as np

In [46]:
a = np.arange(15).reshape(3,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [9]:
a.dtype.name

'int64'

In [10]:
a.itemsize

8

In [11]:
a.size

15

In [12]:
type(a)

numpy.ndarray

In [15]:
b = np.array([6,7,8])
b

array([6, 7, 8])

* this is if I want to create an array that is either True or 1. if it is true we set the dtype to bool

In [6]:
a = np.ones((3,3), dtype=bool)
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

* this is if I want to create an array but not True/1

In [13]:
b = np.full((3,3), -3, dtype=int)
b

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

### Question : Extract all odd numbers from array
### input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
### output: array([1, 3, 5, 7, 9])

In [14]:
arr = np.arange(10)

In [17]:
arr[arr%2==0]

array([0, 2, 4, 6, 8])

#### Question: Replace all odd numbers in arr with -1
#### input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#### output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [18]:
b = np.arange(10)

In [19]:
b[b%2 != 0] = -1
b

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Question: Replace all odd numbers in arr with -1 `without` changing arr
### input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
### output: out
### array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
### arr
### array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
b = np.arange(10)
c = b.copy()
c[c%2 != 0] = -1

print("Original")
print(b)

print("Changed")
print(c)




Original
[0 1 2 3 4 5 6 7 8 9]
Changed
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Question: Convert a 1D array to a 2D array with 2 rows
### input: np.arange(10)
### output array([[0, 1, 2, 3, 4],
###               [5, 6, 7, 8, 9]])

In [39]:
b = np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Question: Stack arrays a and b vertically
### input: a = np.arange(10).reshape(2,-1)
###        b = np.repeat(1, 10).reshape(2,-1)

### output: array([[0, 1, 2, 3, 4],
###                [5, 6, 7, 8, 9],
###                [1, 1, 1, 1, 1],
###                [1, 1, 1, 1, 1]])

In [51]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2, -1)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

### Input: a = np.array([1,2,3])
### Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [59]:
a = np.array([1, 2, 3])
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])